### ISSUE TITLE
Formula for the likelihood function is wrong

### ISSUE THREAD

**Issue by setare92-ha** [learn-co-curriculum/dsc-mle-logistic-regression#1]
## Issue Subtype

- [ x] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```

```

### Concern

![image](https://github.com/user-attachments/assets/284fe1fd-5459-4bc4-b63c-69c118c869de)

## (Optional) Proposed Solution

Correct formula added on the snapshot with red

## What OS Are You Using?

- [ ] OS X
- [x ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by bpurdy-ds** [comment]
Thank you for raising this issue. We'll take a look.

**Comment by bpurdy-ds** [comment]
Yes, you are correct with your suggestion and it has been updated.
